name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      
      - name: Login to docker hub
        run: docker login -u oddgroots -p Odd@91754
      
      - name: Build Docker image
        run: docker build -t oddgroots/nodejs-app .
      
      - name: Push image to Docker Hub
        run: docker push oddgroots/nodejs-app:latest

        

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull oddgroots/nodejs-app:latest
      
      - name: Stop and Remove old container (if exists)
        run: |
          docker stop nodejs-app-container || true
          docker rm nodejs-app-container || true
      
      - name: Run Docker container
        run: |
          docker run -d \
            -p 5000:5000 \
            --name nodejs-app-container \
            oddgroots/nodejs-app:latest